# Generated by Django 2.2.4 on 2019-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baiviet_tieude', models.CharField(max_length=200)),
                ('baiviet_noidung', models.TextField()),
                ('baiviet_ngaydang', models.DateTimeField(verbose_name='Ngày đăng bài')),
            ],
        ),
    ]
