# Generated by Django 2.2.4 on 2019-08-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='baiviet_noidung_rutgon',
            field=models.TextField(default='Nội dung rút gọn', verbose_name='Nội dung rút gọn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='baiviet_noidung',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='baiviet_tieude',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
    ]
