# Generated by Django 2.2.4 on 2019-08-10 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190807_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menutop_ten', models.CharField(max_length=200, verbose_name='Tên menu')),
                ('menutop_duongdan', models.CharField(max_length=200, verbose_name='Đường dẫn')),
            ],
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='baiviet_ngaydang',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Ngày đăng bài'),
        ),
    ]
