# Generated by Django 2.2.4 on 2019-08-31 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190827_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='sanpham_hinhanh',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Đường dẫn hình ảnh'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='sanpham_duongdan',
            field=models.CharField(max_length=200, verbose_name='Đường dẫn'),
        ),
    ]
