# Generated by Django 2.2.4 on 2019-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190831_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='sanpham_duongdan',
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='sanpham_hinhanh',
            field=models.ImageField(upload_to='hinhanh/', verbose_name='Đường dẫn hình ảnh'),
        ),
    ]
