# Generated by Django 2.2.4 on 2019-09-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190905_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='id',
        ),
        migrations.AddField(
            model_name='sanpham',
            name='sanpham_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
