# Generated by Django 2.2.4 on 2019-09-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190906_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congty_ten', models.CharField(max_length=500, verbose_name='Tên công ty')),
                ('congty_dienthoai', models.CharField(max_length=15, verbose_name='Điện thoại')),
                ('congty_hotline', models.CharField(max_length=15, verbose_name='Hotline')),
                ('congty_email', models.CharField(max_length=50, verbose_name='Email')),
                ('congty_diachi', models.CharField(max_length=1000, verbose_name='Địa chỉ')),
                ('congty_xuongsanxuat', models.CharField(max_length=1000, verbose_name='Xưởng sản xuất')),
                ('congty_logo', models.ImageField(upload_to='logo_congty', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Phongban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenphong', models.CharField(max_length=100, verbose_name='Tên phòng')),
                ('sodienthoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
            ],
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='sanpham_hinhanh',
            field=models.ImageField(upload_to='anhsanpham/', verbose_name='Đường dẫn hình ảnh'),
        ),
    ]
