# Generated by Django 2.2.6 on 2019-11-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190908_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baiviet',
            options={'verbose_name_plural': 'Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='congty',
            options={'verbose_name_plural': 'Công ty'},
        ),
        migrations.AlterModelOptions(
            name='phongban',
            options={'verbose_name_plural': 'Phòng ban'},
        ),
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AddField(
            model_name='baiviet',
            name='baiviet_hinhanh',
            field=models.ImageField(default=None, upload_to='anhbia/', verbose_name='Ảnh bìa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baiviet',
            name='baiviet_sanpham',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='website.Sanpham', verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='baiviet_slug',
            field=models.CharField(default=1, max_length=200, verbose_name='Đường dẫn rút gọn'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='sanpham_slug',
            field=models.CharField(default=1, max_length=200, verbose_name='Đường dẫn rút gọn'),
        ),
    ]
