# Generated by Django 2.2.6 on 2019-11-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20191112_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='baiviet_slug',
            field=models.SlugField(default=1, verbose_name='Đường dẫn rút gọn'),
        ),
    ]
