# Generated by Django 2.2.4 on 2019-11-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20191112_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='phongban',
            name='chucvu',
            field=models.CharField(default='1', max_length=50, verbose_name='Chức vụ'),
            preserve_default=False,
        ),
    ]
