# Generated by Django 2.2.4 on 2020-01-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_phongban_chucvu'),
    ]

    operations = [
        migrations.AddField(
            model_name='congty',
            name='congty_banner',
            field=models.ImageField(default='1', upload_to='banner', verbose_name='Banner'),
        ),
    ]
