# Generated by Django 2.2.4 on 2020-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_congty_congty_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucSanPham',
            fields=[
                ('danh_muc_id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(default=1, verbose_name='Đường dẫn rút gọn')),
            ],
            options={
                'verbose_name_plural': 'Danh mục sản phẩm',
            },
        ),
        migrations.AlterField(
            model_name='congty',
            name='congty_banner',
            field=models.ImageField(default='banner/top_banner.png', upload_to='banner', verbose_name='Banner'),
        ),
    ]
