# Generated by Django 2.2.4 on 2020-01-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200108_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanphamCon',
            fields=[
                ('sanpham_id', models.AutoField(primary_key=True, serialize=False)),
                ('sanpham_ten', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('sanpham_hinhanh', models.ImageField(upload_to='anhsanpham/', verbose_name='Đường dẫn hình ảnh')),
                ('sanpham_giatien', models.CharField(max_length=50, verbose_name='Giá tiền')),
                ('sanpham_slug', models.SlugField(default=1, verbose_name='Đường dẫn rút gọn')),
                ('baiviet_sanpham', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='website.Sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm con',
            },
        ),
        migrations.DeleteModel(
            name='DanhMucSanPham',
        ),
    ]
